# Go2 deploy to sim config
policy_path: "{HIMLOCO_ROOT_DIR}/deploy/models/policy.pt"
xml_path: "{HIMLOCO_ROOT_DIR}/source/himloco_lab/robot_description/go2_description/scene.xml"

# 模拟总时间
simulation_duration: 60.0
# 模拟时间步
simulation_dt: 0.002
# 控制器更新频率 (满足 simulation_dt * control_decimation=0.02; 50Hz)
control_decimation: 10

# MuJoCo 关节映射
joint_mapping: [3, 4, 5, 0, 1, 2, 9, 10, 11, 6, 7, 8]


# PD控制增益
kps: [25.0, 25.0, 25.0, 
      25.0, 25.0, 25.0, 
      25.0, 25.0, 25.0, 
      25.0, 25.0, 25.0]

kds: [0.5, 0.5, 0.5, 
      0.5, 0.5, 0.5, 
      0.5, 0.5, 0.5, 
      0.5, 0.5, 0.5]

# 力矩限制（按关节：FR/FL/RR/RL，每条腿 [hip, thigh, calf]）
torque_limits: [23.7, 23.7, 45.4,
                23.7, 23.7, 45.4,
                23.7, 23.7, 45.4,
                23.7, 23.7, 45.4]

# 默认关节位置
# 每条腿 [hip, thigh, calf]
default_angles: [ 0.1000,  0.8000, -1.5000,   # FL
                 -0.1000,  0.8000, -1.5000,   # FR
                  0.1000,  1.0000, -1.5000,   # RL
                 -0.1000,  1.0000, -1.5000]   # RR

# 观测归一化缩放
ang_vel_scale: 0.25
dof_pos_scale: 1.0
dof_vel_scale: 0.05
action_scale: 0.25
cmd_scale: [2.0, 2.0, 0.25]  # [lin_vel_x, lin_vel_y, ang_vel_yaw]

# 观测和动作维度
num_actions: 12
num_obs: 45

# 最大运动指令限制 [lin_vel_x, lin_vel_y, ang_vel_yaw]
max_cmd: [1.0, 1.0, 1.0]

# 初始运动指令
cmd_init: [1.0, 0.0, 0.0]
